### ISSUE TITLE
Inconsistency and issues when adding links

### ISSUE THREAD

**Issue by joebno** [damyon/moodle-editor_atto#21]
There are a number of issues with Atto when attempting to add links - depending upon browser and OS, Atto either behaves differently, or doesn't work as intended.  Here is the breakdown:

**PC (Windows 7/8)**
    1. Firefox:  
        \* Selecting a word or block of text and then adding a link works as expected
      \* Attempting to insert a link without selecting any text does nothing at all
    2. Chrome: 
      \* Selecting a word or block of text and then adding a link works as expected
      \* Inserting a link without selecting any text works and uses the link as the text for the link
**Mac**
    1. Chrome & Safari:
      *Selecting a word or block of text and then adding a link does not work - it simply adds the link after the selected text, with the link as the text for the link.

Everything works as it should if the link is inserted through code.

**Comment by damyon** [comment]
Thanks - this is partly due to inconsistencies between browsers themselves. The 2.6 version of Atto is a thin wrapper around browsers implementations of "contenteditable" regions - and as different browsers implement this differently there can be varying results. That said - when we rewrote Atto for 2.7 we did a heap of testing and provided workarounds for these cases. Short answer - Atto in the plugins DB will show some of these issues, Atto in core for 2.7 will work much better.
