### ISSUE TITLE
Atto-Editor not showing/missing

### ISSUE THREAD

**Issue by jps24** [damyon/moodle-editor_atto#22]
I recently noticed that the Atto-Editor was missing all of a sudden. I don't remember changing anything and i just made sure that atto is enabled and set as the standard-editor. However it just doesn't show up when i try to add new Material like texts or try to edit existing stuff. Also i'm not able to add files to a forum-post for example. There's just a spinning wheel where the upload dialog used to be. If i change the standard-editor to tinymce it all shows up properly, but i really would prefer using Atto. The issue is not browser-specific: i tried firefox, chrome and ie, none worked. Do you guys have any suggestions on how to solve this or what might be causing this issue?
I'm using Moodle 2.7.1
Thanks in advance,
Jan

**Comment by damyon** [comment]
Hi - this github is only for the Atto version in the plugins DB which is for Moodle 2.6 and lower. It was the prototype for the full fledged Atto in 2.7. 

The specific problem you are having might be because MathJAX changed their urls for their CDN - there is a bug in the moodle tracker about this and it has been fixed in the weeklies (2.7.1+). 

https://tracker.moodle.org/browse/MDL-46748
